---
title: "API documentation"
format:
    html: 
        grid: 
          body-width: 1300px
authors:
    - Gabriel LORGET
    - Hugo TRICOIRE
---

# Endpoint /city (Méthode HTTP GET)

## Description :
L'Endpoint a en paramètre les coordonnées en latitude et longitude avec des filtres établis (distance maximale définissant un rayon, population minimale, nombre de villes à retourner, régions prises en compte) et renvoie la liste des villes correspondantes sous format csv (avec les informations correspondantes).

## Paramètres de requête :
- latitude (obligatoire) : la latitude de la position géographique.
- longitude (obligatoire) : la longitude de la position géographique.
- distance (obligatoire) : la distance maximale (en kilomètres) à partir des coordonnées spécifiées.
- min_pop (obligatoire) : la population minimale que doivent avoir les villes renvoyées.
- number (obligatoire) : le nombre de villes à retourner (classées de la plus proche à la plus loin du point)
- regions (obligatoire, nul si non spécifié) : une liste de régions à prendre en compte pour filtrer les villes.

## Réponses :
- Code 200 OK : renvoie une liste de villes au format CSV.
- Code 400 Bad Request : indique que des paramètres obligatoires sont manquants ou invalides.
- Code 404 Not Found : indique qu'aucune ville n'a été trouvée pour les paramètres spécifiés.

## Exemple de requête :
http://localhost:5000/city?latitude=48.8566&longitude=2.3522&distance=10000&min_pop=7000&number=20&regions=Ile%20de%20France,Pays%20de%20la%20Loire

## Exemple de réponse :
Ville,Région,Latitude,Longitude,Population,Distance
La Ferte-Bernard,Pays de la Loire,48.1867,0.6544,8852,142.38111126997777
Coulaines,Pays de la Loire,48.0267,0.2042,7600,179.31283811803831
Le Mans,Pays de la Loire,48.0077,0.1984,143252,180.57864509968667
Allonnes,Pays de la Loire,47.9686,0.1606,11075,184.89794882730536
La Fleche,Pays de la Loire,47.6997,-0.0761,14902,213.7152204068269
Evron,Pays de la Loire,48.1556,-0.4025,7048,215.56417750224614
Sable-sur-Sarthe,Pays de la Loire,47.84,-0.3342,12127,223.27930433791778
Mayenne,Pays de la Loire,48.3031,-0.6136,12874,226.3412164638457
Saumur,Pays de la Loire,47.26,-0.0769,26599,240.42182503312054
Laval,Pays de la Loire,48.0733,-0.7689,49573,243.88268836833717
Saint-Berthevin,Pays de la Loire,48.0683,-0.8258,7348,248.0323864225783
Chateau-Gontier,Pays de la Loire,47.8286,-0.7028,11805,248.34541735409397
Trelaze,Pays de la Loire,47.4461,-0.4664,14759,251.7921051906554
Saint-Barthelemy-d Anjou,Pays de la Loire,47.4675,-0.495,9203,252.36378134375587
Angers,Pays de la Loire,47.4736,-0.5542,154508,255.70214166209706
Doue-la-Fontaine,Pays de la Loire,47.1931,-0.2756,7686,255.90217965120897
Avrille,Pays de la Loire,47.5069,-0.5889,14065,256.0950206378446
Montreuil-Juigne,Pays de la Loire,47.5283,-0.6119,7521,256.427966879092
Les Ponts-de-Ce,Pays de la Loire,47.4244,-0.5253,12811,256.618927598318
Chemille,Pays de la Loire,47.2131,-0.7258,7201,280.87540207490173