@carte_france_interactive_HostAddress = http://localhost:5191

### Requête GET pour la méthode MapGet
GET {{carte_france_interactive_HostAddress}}/city/{{latitude}}/{{longitude}}
Accept: application/json

### Requête POST pour la méthode MapPost
POST {{carte_france_interactive_HostAddress}}/city
Content-Type: application/json

{
    "latitude": {{latitude}},
    "longitude": {{longitude}}
}
