@carte_france_interactive_HostAddress = http://localhost:5000

### Requête GET pour la méthode MapGet
GET {{carte_france_interactive_HostAddress}}/city?latitude=48.8566&longitude=2.3522&distance=100&max_pop=2000000 HTTP/1.1