version: '3'

services:
  api_carte_france:
    image: hugoth85/projet_carte_france:api
    container_name: api_carte_france
    networks:
      - backend_carte_france
    ports:
      - "5000:8080"
    restart: always

  db_carte_france:
    image: hugoth85/projet_carte_france:database
    container_name: db_carte_france
    networks:
      backend_carte_france:
        ipv4_address: "172.23.0.3"
    ports:
      - "3310:3310"
    restart: always
  front_carte_france:
    image: cmooooi/cdf:1.16
    container_name: front_carte_france
    networks:
      backend_carte_france:
        ipv4_address: "172.23.0.4"
    ports:
      - "3000:3000"
    restart: always

networks:
  backend_carte_france:
    ipam:
      driver: default
      config:
        - subnet: 172.23.0.0/16