# Utilisez l'image officielle MySQL
FROM mysql:latest

# Informations d'identification pour créer la base de données et l'utilisateur
ENV MYSQL_DATABASE=projet_archi2 \
    MYSQL_ROOT_PASSWORD=root

# Ajoutez un script SQL pour initialiser la base de données (si nécessaire)
COPY db_cities.sql /docker-entrypoint-initdb.d/

#RUN touch /etc/mysql/my.cnf && echo -e "[mysqld]\nbinary-mode=1"